from typing import List, Optional
from pydantic import BaseModel, Field
from backend.schemas.event import EventResponse

class ConversationTurn(BaseModel):
    question: str = Field(..., description="The user's question in this conversation turn")
    answer: str = Field(..., description="The assistant's response in this conversation turn")

class QueryRequest(BaseModel):
    question: str = Field(..., min_length=1, description="The natural language question to ask EchoMind")
    conversation_history: Optional[List[ConversationTurn]] = Field(None, description="Optional conversation history (up to last 3 exchanges)")

class QueryResponse(BaseModel):
    answer: str = Field(..., description="The grounded answer generated by the assistant")
    referenced_events: List[EventResponse] = Field(..., description="The list of database events referenced to formulate the answer")
    mode: str = Field(..., description="The LLM execution mode ('mock', 'live', or 'mock_fallback')")

