from typing import List
from pydantic import BaseModel, Field
from backend.schemas.event import EventResponse

class QueryRequest(BaseModel):
    question: str = Field(..., min_length=1, description="The natural language question to ask EchoMind")

class QueryResponse(BaseModel):
    answer: str = Field(..., description="The grounded answer generated by the assistant")
    referenced_events: List[EventResponse] = Field(..., description="The list of database events referenced to formulate the answer")
    mode: str = Field(..., description="The LLM execution mode ('mock' or 'live')")
